
microservice.contextpath: '/api/v1/test'

server.port: 8181

spring:
  application:
   name: discovery-service-demo
  profiles: default
  cloud:
    config:
      enabled: true


eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistery: true
  serviceUrl:
    defaultZone: http://localhost:8761/eureka/

